# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QGraphicsView,
    QLabel, QPushButton, QSizePolicy, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(900, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QSize(900, 600))
        Dialog.setMaximumSize(QSize(1200, 900))
        self.button_forecast0 = QPushButton(Dialog)
        self.button_forecast0.setObjectName(u"button_forecast0")
        self.button_forecast0.setEnabled(True)
        self.button_forecast0.setGeometry(QRect(100, 170, 101, 25))
        font = QFont()
        font.setFamilies([u"Lucida Sans Unicode"])
        font.setPointSize(10)
        self.button_forecast0.setFont(font)
        self.button_forecast0.setFlat(False)
        self.button_forecast1 = QPushButton(Dialog)
        self.button_forecast1.setObjectName(u"button_forecast1")
        self.button_forecast1.setGeometry(QRect(400, 170, 101, 25))
        self.button_forecast1.setFont(font)
        self.button_forecast2 = QPushButton(Dialog)
        self.button_forecast2.setObjectName(u"button_forecast2")
        self.button_forecast2.setGeometry(QRect(699, 170, 101, 25))
        self.button_forecast2.setFont(font)
        self.button_add0 = QPushButton(Dialog)
        self.button_add0.setObjectName(u"button_add0")
        self.button_add0.setGeometry(QRect(120, 320, 50, 50))
        font1 = QFont()
        font1.setFamilies([u"Tahoma"])
        font1.setPointSize(26)
        self.button_add0.setFont(font1)
        self.button_add1 = QPushButton(Dialog)
        self.button_add1.setObjectName(u"button_add1")
        self.button_add1.setGeometry(QRect(430, 320, 50, 50))
        self.button_add1.setFont(font1)
        self.button_add2 = QPushButton(Dialog)
        self.button_add2.setObjectName(u"button_add2")
        self.button_add2.setGeometry(QRect(730, 320, 50, 50))
        self.button_add2.setFont(font1)
        self.line = QFrame(Dialog)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(290, 40, 16, 741))
        self.line.setMinimumSize(QSize(10, 0))
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(10)
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(Dialog)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(598, 40, 16, 571))
        self.line_2.setMinimumSize(QSize(10, 0))
        self.line_2.setLineWidth(0)
        self.line_2.setMidLineWidth(10)
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_3 = QFrame(Dialog)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setEnabled(True)
        self.line_3.setGeometry(QRect(0, 35, 901, 16))
        self.line_3.setMinimumSize(QSize(0, 10))
        self.line_3.setBaseSize(QSize(4, 5))
        font2 = QFont()
        font2.setBold(True)
        self.line_3.setFont(font2)
        self.line_3.setLineWidth(0)
        self.line_3.setMidLineWidth(10)
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(-10, -1, 921, 41))
        font3 = QFont()
        font3.setFamilies([u"Trebuchet MS"])
        font3.setPointSize(16)
        font3.setBold(False)
        self.label.setFont(font3)
        self.label.setAlignment(Qt.AlignCenter)
        self.graphicsView_main0 = QGraphicsView(Dialog)
        self.graphicsView_main0.setObjectName(u"graphicsView_main0")
        self.graphicsView_main0.setGeometry(QRect(10, 214, 151, 131))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.graphicsView_main0.sizePolicy().hasHeightForWidth())
        self.graphicsView_main0.setSizePolicy(sizePolicy1)
        self.graphicsView_main0.setMinimumSize(QSize(125, 125))
        self.graphicsView_main0.setMaximumSize(QSize(200, 200))
        self.graphicsView_main1 = QGraphicsView(Dialog)
        self.graphicsView_main1.setObjectName(u"graphicsView_main1")
        self.graphicsView_main1.setGeometry(QRect(320, 214, 151, 131))
        sizePolicy1.setHeightForWidth(self.graphicsView_main1.sizePolicy().hasHeightForWidth())
        self.graphicsView_main1.setSizePolicy(sizePolicy1)
        self.graphicsView_main1.setMinimumSize(QSize(125, 125))
        self.graphicsView_main1.setMaximumSize(QSize(200, 200))
        self.graphicsView_main2 = QGraphicsView(Dialog)
        self.graphicsView_main2.setObjectName(u"graphicsView_main2")
        self.graphicsView_main2.setGeometry(QRect(620, 214, 151, 131))
        sizePolicy1.setHeightForWidth(self.graphicsView_main2.sizePolicy().hasHeightForWidth())
        self.graphicsView_main2.setSizePolicy(sizePolicy1)
        self.graphicsView_main2.setMinimumSize(QSize(125, 125))
        self.graphicsView_main2.setMaximumSize(QSize(200, 200))
        self.day0Temp = QLabel(Dialog)
        self.day0Temp.setObjectName(u"day0Temp")
        self.day0Temp.setGeometry(QRect(170, 230, 101, 90))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(80)
        sizePolicy2.setVerticalStretch(90)
        sizePolicy2.setHeightForWidth(self.day0Temp.sizePolicy().hasHeightForWidth())
        self.day0Temp.setSizePolicy(sizePolicy2)
        self.day0Temp.setMinimumSize(QSize(80, 90))
        self.day0Temp.setMaximumSize(QSize(999999, 999999))
        font4 = QFont()
        font4.setFamilies([u"Comic Sans MS"])
        font4.setPointSize(22)
        self.day0Temp.setFont(font4)
        self.day0Temp.setAlignment(Qt.AlignCenter)
        self.day1Temp = QLabel(Dialog)
        self.day1Temp.setObjectName(u"day1Temp")
        self.day1Temp.setGeometry(QRect(480, 230, 101, 90))
        sizePolicy2.setHeightForWidth(self.day1Temp.sizePolicy().hasHeightForWidth())
        self.day1Temp.setSizePolicy(sizePolicy2)
        self.day1Temp.setMinimumSize(QSize(80, 90))
        self.day1Temp.setMaximumSize(QSize(99999, 99999))
        self.day1Temp.setFont(font4)
        self.day1Temp.setAlignment(Qt.AlignCenter)
        self.day2Temp = QLabel(Dialog)
        self.day2Temp.setObjectName(u"day2Temp")
        self.day2Temp.setGeometry(QRect(780, 230, 101, 90))
        sizePolicy2.setHeightForWidth(self.day2Temp.sizePolicy().hasHeightForWidth())
        self.day2Temp.setSizePolicy(sizePolicy2)
        self.day2Temp.setMinimumSize(QSize(80, 90))
        self.day2Temp.setMaximumSize(QSize(99999, 99999))
        self.day2Temp.setFont(font4)
        self.day2Temp.setAlignment(Qt.AlignCenter)
        self.day0Loc = QLabel(Dialog)
        self.day0Loc.setObjectName(u"day0Loc")
        self.day0Loc.setGeometry(QRect(-1, 110, 301, 60))
        sizePolicy.setHeightForWidth(self.day0Loc.sizePolicy().hasHeightForWidth())
        self.day0Loc.setSizePolicy(sizePolicy)
        font5 = QFont()
        font5.setFamilies([u"Tahoma"])
        font5.setPointSize(20)
        font5.setBold(False)
        font5.setItalic(False)
        self.day0Loc.setFont(font5)
        self.day0Loc.setAlignment(Qt.AlignCenter)
        self.day1Loc = QLabel(Dialog)
        self.day1Loc.setObjectName(u"day1Loc")
        self.day1Loc.setGeometry(QRect(299, 110, 301, 60))
        sizePolicy.setHeightForWidth(self.day1Loc.sizePolicy().hasHeightForWidth())
        self.day1Loc.setSizePolicy(sizePolicy)
        self.day1Loc.setMinimumSize(QSize(200, 60))
        self.day1Loc.setMaximumSize(QSize(999999, 999999))
        font6 = QFont()
        font6.setFamilies([u"Tahoma"])
        font6.setPointSize(20)
        self.day1Loc.setFont(font6)
        self.day1Loc.setAlignment(Qt.AlignCenter)
        self.day2Loc = QLabel(Dialog)
        self.day2Loc.setObjectName(u"day2Loc")
        self.day2Loc.setGeometry(QRect(599, 110, 301, 60))
        sizePolicy.setHeightForWidth(self.day2Loc.sizePolicy().hasHeightForWidth())
        self.day2Loc.setSizePolicy(sizePolicy)
        self.day2Loc.setMinimumSize(QSize(200, 60))
        self.day2Loc.setMaximumSize(QSize(9999999, 9999999))
        self.day2Loc.setFont(font6)
        self.day2Loc.setAlignment(Qt.AlignCenter)
        self.day0Desc = QLabel(Dialog)
        self.day0Desc.setObjectName(u"day0Desc")
        self.day0Desc.setGeometry(QRect(10, 320, 151, 61))
        self.day0Desc.setMinimumSize(QSize(90, 40))
        self.day0Desc.setMaximumSize(QSize(300, 125))
        font7 = QFont()
        font7.setFamilies([u"Comic Sans MS"])
        font7.setPointSize(13)
        self.day0Desc.setFont(font7)
        self.day0Desc.setAlignment(Qt.AlignCenter)
        self.day0Desc.setWordWrap(True)
        self.day0Date = QLabel(Dialog)
        self.day0Date.setObjectName(u"day0Date")
        self.day0Date.setGeometry(QRect(70, 500, 151, 75))
        self.day0Date.setMinimumSize(QSize(115, 60))
        font8 = QFont()
        font8.setFamilies([u"Verdana"])
        font8.setPointSize(14)
        self.day0Date.setFont(font8)
        self.day0Date.setAlignment(Qt.AlignCenter)
        self.day0Date.setWordWrap(True)
        self.day0RiseSymb = QLabel(Dialog)
        self.day0RiseSymb.setObjectName(u"day0RiseSymb")
        self.day0RiseSymb.setGeometry(QRect(10, 510, 80, 40))
        self.day0RiseSymb.setMinimumSize(QSize(80, 40))
        self.day0RiseSymb.setMaximumSize(QSize(80, 40))
        font9 = QFont()
        font9.setFamilies([u"Verdana"])
        font9.setPointSize(26)
        self.day0RiseSymb.setFont(font9)
        self.day0RiseSymb.setAlignment(Qt.AlignCenter)
        self.day0RiseSymb.setWordWrap(True)
        self.day0SetSymb = QLabel(Dialog)
        self.day0SetSymb.setObjectName(u"day0SetSymb")
        self.day0SetSymb.setGeometry(QRect(200, 510, 80, 40))
        self.day0SetSymb.setMinimumSize(QSize(80, 40))
        self.day0SetSymb.setMaximumSize(QSize(80, 40))
        self.day0SetSymb.setFont(font9)
        self.day0SetSymb.setAlignment(Qt.AlignCenter)
        self.day0SetSymb.setWordWrap(True)
        self.day1RiseSymb = QLabel(Dialog)
        self.day1RiseSymb.setObjectName(u"day1RiseSymb")
        self.day1RiseSymb.setGeometry(QRect(320, 510, 80, 40))
        self.day1RiseSymb.setMinimumSize(QSize(80, 40))
        self.day1RiseSymb.setMaximumSize(QSize(80, 40))
        self.day1RiseSymb.setFont(font9)
        self.day1RiseSymb.setAlignment(Qt.AlignCenter)
        self.day1RiseSymb.setWordWrap(True)
        self.day1SetSymb = QLabel(Dialog)
        self.day1SetSymb.setObjectName(u"day1SetSymb")
        self.day1SetSymb.setGeometry(QRect(510, 510, 80, 40))
        self.day1SetSymb.setMinimumSize(QSize(80, 40))
        self.day1SetSymb.setMaximumSize(QSize(80, 40))
        self.day1SetSymb.setFont(font9)
        self.day1SetSymb.setAlignment(Qt.AlignCenter)
        self.day1SetSymb.setWordWrap(True)
        self.day2RiseSymb = QLabel(Dialog)
        self.day2RiseSymb.setObjectName(u"day2RiseSymb")
        self.day2RiseSymb.setGeometry(QRect(620, 510, 80, 40))
        self.day2RiseSymb.setMinimumSize(QSize(80, 40))
        self.day2RiseSymb.setMaximumSize(QSize(80, 40))
        self.day2RiseSymb.setFont(font9)
        self.day2RiseSymb.setAlignment(Qt.AlignCenter)
        self.day2RiseSymb.setWordWrap(True)
        self.day2SetSymb = QLabel(Dialog)
        self.day2SetSymb.setObjectName(u"day2SetSymb")
        self.day2SetSymb.setGeometry(QRect(810, 510, 80, 40))
        self.day2SetSymb.setMinimumSize(QSize(80, 40))
        self.day2SetSymb.setMaximumSize(QSize(80, 40))
        self.day2SetSymb.setFont(font9)
        self.day2SetSymb.setAlignment(Qt.AlignCenter)
        self.day2SetSymb.setWordWrap(True)
        self.day0Humid = QLabel(Dialog)
        self.day0Humid.setObjectName(u"day0Humid")
        self.day0Humid.setGeometry(QRect(10, 400, 115, 51))
        self.day0Humid.setMinimumSize(QSize(115, 40))
        self.day0Humid.setMaximumSize(QSize(115, 75))
        font10 = QFont()
        font10.setFamilies([u"Verdana"])
        font10.setPointSize(11)
        self.day0Humid.setFont(font10)
        self.day0Humid.setAlignment(Qt.AlignCenter)
        self.day0Humid.setWordWrap(True)
        self.day0Wind = QLabel(Dialog)
        self.day0Wind.setObjectName(u"day0Wind")
        self.day0Wind.setGeometry(QRect(170, 400, 115, 51))
        self.day0Wind.setMinimumSize(QSize(115, 40))
        self.day0Wind.setMaximumSize(QSize(115, 75))
        self.day0Wind.setFont(font10)
        self.day0Wind.setAlignment(Qt.AlignCenter)
        self.day0Wind.setWordWrap(True)
        self.day0SunRise = QLabel(Dialog)
        self.day0SunRise.setObjectName(u"day0SunRise")
        self.day0SunRise.setGeometry(QRect(10, 480, 80, 30))
        self.day0SunRise.setMinimumSize(QSize(80, 30))
        self.day0SunRise.setMaximumSize(QSize(80, 30))
        font11 = QFont()
        font11.setFamilies([u"Lucida Sans Unicode"])
        font11.setPointSize(11)
        self.day0SunRise.setFont(font11)
        self.day0SunRise.setAlignment(Qt.AlignCenter)
        self.day0SunSet = QLabel(Dialog)
        self.day0SunSet.setObjectName(u"day0SunSet")
        self.day0SunSet.setGeometry(QRect(200, 480, 80, 30))
        self.day0SunSet.setMinimumSize(QSize(80, 30))
        self.day0SunSet.setMaximumSize(QSize(80, 30))
        self.day0SunSet.setFont(font11)
        self.day0SunSet.setAlignment(Qt.AlignCenter)
        self.day1SunSet = QLabel(Dialog)
        self.day1SunSet.setObjectName(u"day1SunSet")
        self.day1SunSet.setGeometry(QRect(510, 480, 80, 30))
        self.day1SunSet.setMinimumSize(QSize(80, 30))
        self.day1SunSet.setMaximumSize(QSize(80, 30))
        self.day1SunSet.setFont(font11)
        self.day1SunSet.setAlignment(Qt.AlignCenter)
        self.day1SunRise = QLabel(Dialog)
        self.day1SunRise.setObjectName(u"day1SunRise")
        self.day1SunRise.setGeometry(QRect(320, 480, 80, 30))
        self.day1SunRise.setMinimumSize(QSize(80, 30))
        self.day1SunRise.setMaximumSize(QSize(80, 30))
        self.day1SunRise.setFont(font11)
        self.day1SunRise.setAlignment(Qt.AlignCenter)
        self.day2SunSet = QLabel(Dialog)
        self.day2SunSet.setObjectName(u"day2SunSet")
        self.day2SunSet.setGeometry(QRect(810, 480, 80, 30))
        self.day2SunSet.setMinimumSize(QSize(80, 30))
        self.day2SunSet.setMaximumSize(QSize(80, 30))
        self.day2SunSet.setFont(font11)
        self.day2SunSet.setAlignment(Qt.AlignCenter)
        self.day2SunRise = QLabel(Dialog)
        self.day2SunRise.setObjectName(u"day2SunRise")
        self.day2SunRise.setGeometry(QRect(620, 480, 80, 30))
        self.day2SunRise.setMinimumSize(QSize(80, 30))
        self.day2SunRise.setMaximumSize(QSize(80, 30))
        self.day2SunRise.setFont(font11)
        self.day2SunRise.setAlignment(Qt.AlignCenter)
        self.button_clear0 = QPushButton(Dialog)
        self.button_clear0.setObjectName(u"button_clear0")
        self.button_clear0.setGeometry(QRect(100, 80, 101, 29))
        self.button_clear0.setFont(font)
        self.button_clear1 = QPushButton(Dialog)
        self.button_clear1.setObjectName(u"button_clear1")
        self.button_clear1.setGeometry(QRect(400, 80, 101, 29))
        self.button_clear1.setFont(font)
        self.button_clear2 = QPushButton(Dialog)
        self.button_clear2.setObjectName(u"button_clear2")
        self.button_clear2.setGeometry(QRect(700, 80, 101, 29))
        self.button_clear2.setFont(font)
        self.day0RiseLabel = QLabel(Dialog)
        self.day0RiseLabel.setObjectName(u"day0RiseLabel")
        self.day0RiseLabel.setGeometry(QRect(20, 550, 61, 31))
        font12 = QFont()
        font12.setFamilies([u"Comic Sans MS"])
        font12.setPointSize(13)
        font12.setBold(False)
        self.day0RiseLabel.setFont(font12)
        self.day1RiseLabel = QLabel(Dialog)
        self.day1RiseLabel.setObjectName(u"day1RiseLabel")
        self.day1RiseLabel.setGeometry(QRect(330, 550, 61, 31))
        self.day1RiseLabel.setFont(font12)
        self.day2RiseLabel = QLabel(Dialog)
        self.day2RiseLabel.setObjectName(u"day2RiseLabel")
        self.day2RiseLabel.setGeometry(QRect(630, 550, 61, 31))
        self.day2RiseLabel.setFont(font12)
        self.day0SetLabel = QLabel(Dialog)
        self.day0SetLabel.setObjectName(u"day0SetLabel")
        self.day0SetLabel.setGeometry(QRect(210, 550, 63, 31))
        self.day0SetLabel.setFont(font12)
        self.day1SetLabel = QLabel(Dialog)
        self.day1SetLabel.setObjectName(u"day1SetLabel")
        self.day1SetLabel.setGeometry(QRect(520, 550, 63, 31))
        self.day1SetLabel.setFont(font12)
        self.day2SetLabel = QLabel(Dialog)
        self.day2SetLabel.setObjectName(u"day2SetLabel")
        self.day2SetLabel.setGeometry(QRect(820, 550, 63, 31))
        self.day2SetLabel.setFont(font12)
        self.day1Desc = QLabel(Dialog)
        self.day1Desc.setObjectName(u"day1Desc")
        self.day1Desc.setGeometry(QRect(320, 320, 151, 61))
        self.day1Desc.setMinimumSize(QSize(90, 40))
        self.day1Desc.setMaximumSize(QSize(300, 125))
        self.day1Desc.setFont(font7)
        self.day1Desc.setAlignment(Qt.AlignCenter)
        self.day1Desc.setWordWrap(True)
        self.day2Desc = QLabel(Dialog)
        self.day2Desc.setObjectName(u"day2Desc")
        self.day2Desc.setGeometry(QRect(620, 320, 151, 61))
        self.day2Desc.setMinimumSize(QSize(90, 40))
        self.day2Desc.setMaximumSize(QSize(300, 125))
        self.day2Desc.setFont(font7)
        self.day2Desc.setAlignment(Qt.AlignCenter)
        self.day2Desc.setWordWrap(True)
        self.day1Date = QLabel(Dialog)
        self.day1Date.setObjectName(u"day1Date")
        self.day1Date.setGeometry(QRect(380, 500, 151, 75))
        self.day1Date.setMinimumSize(QSize(115, 60))
        self.day1Date.setFont(font8)
        self.day1Date.setAlignment(Qt.AlignCenter)
        self.day1Date.setWordWrap(True)
        self.day2Date = QLabel(Dialog)
        self.day2Date.setObjectName(u"day2Date")
        self.day2Date.setGeometry(QRect(680, 500, 151, 71))
        self.day2Date.setMinimumSize(QSize(115, 60))
        self.day2Date.setFont(font8)
        self.day2Date.setAlignment(Qt.AlignCenter)
        self.day2Date.setWordWrap(True)
        self.addLocation0 = QLabel(Dialog)
        self.addLocation0.setObjectName(u"addLocation0")
        self.addLocation0.setGeometry(QRect(90, 370, 111, 31))
        font13 = QFont()
        font13.setFamilies([u"Tahoma"])
        font13.setPointSize(14)
        self.addLocation0.setFont(font13)
        self.addLocation0.setAlignment(Qt.AlignCenter)
        self.addLocation1 = QLabel(Dialog)
        self.addLocation1.setObjectName(u"addLocation1")
        self.addLocation1.setGeometry(QRect(400, 370, 111, 31))
        self.addLocation1.setFont(font13)
        self.addLocation1.setAlignment(Qt.AlignCenter)
        self.addLocation2 = QLabel(Dialog)
        self.addLocation2.setObjectName(u"addLocation2")
        self.addLocation2.setGeometry(QRect(700, 370, 111, 31))
        self.addLocation2.setFont(font13)
        self.addLocation2.setAlignment(Qt.AlignCenter)
        self.day1Humid = QLabel(Dialog)
        self.day1Humid.setObjectName(u"day1Humid")
        self.day1Humid.setGeometry(QRect(310, 400, 115, 51))
        self.day1Humid.setMinimumSize(QSize(115, 40))
        self.day1Humid.setMaximumSize(QSize(115, 75))
        self.day1Humid.setFont(font10)
        self.day1Humid.setAlignment(Qt.AlignCenter)
        self.day1Humid.setWordWrap(True)
        self.day2Humid = QLabel(Dialog)
        self.day2Humid.setObjectName(u"day2Humid")
        self.day2Humid.setGeometry(QRect(620, 400, 115, 51))
        self.day2Humid.setMinimumSize(QSize(115, 40))
        self.day2Humid.setMaximumSize(QSize(115, 75))
        self.day2Humid.setFont(font10)
        self.day2Humid.setAlignment(Qt.AlignCenter)
        self.day2Humid.setWordWrap(True)
        self.day1Wind = QLabel(Dialog)
        self.day1Wind.setObjectName(u"day1Wind")
        self.day1Wind.setGeometry(QRect(480, 400, 115, 51))
        self.day1Wind.setMinimumSize(QSize(115, 40))
        self.day1Wind.setMaximumSize(QSize(115, 75))
        self.day1Wind.setFont(font10)
        self.day1Wind.setAlignment(Qt.AlignCenter)
        self.day1Wind.setWordWrap(True)
        self.day2Wind = QLabel(Dialog)
        self.day2Wind.setObjectName(u"day2Wind")
        self.day2Wind.setGeometry(QRect(780, 400, 115, 51))
        self.day2Wind.setMinimumSize(QSize(115, 40))
        self.day2Wind.setMaximumSize(QSize(115, 75))
        self.day2Wind.setFont(font10)
        self.day2Wind.setAlignment(Qt.AlignCenter)
        self.day2Wind.setWordWrap(True)
        self.button_forecast0.raise_()
        self.button_forecast1.raise_()
        self.button_forecast2.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.label.raise_()
        self.graphicsView_main0.raise_()
        self.graphicsView_main1.raise_()
        self.graphicsView_main2.raise_()
        self.day0Temp.raise_()
        self.day1Temp.raise_()
        self.day2Temp.raise_()
        self.day0Loc.raise_()
        self.day1Loc.raise_()
        self.day2Loc.raise_()
        self.day0Desc.raise_()
        self.day0Date.raise_()
        self.day0RiseSymb.raise_()
        self.day0SetSymb.raise_()
        self.day1RiseSymb.raise_()
        self.day1SetSymb.raise_()
        self.day2RiseSymb.raise_()
        self.day2SetSymb.raise_()
        self.day0Humid.raise_()
        self.day0Wind.raise_()
        self.day0SunRise.raise_()
        self.day0SunSet.raise_()
        self.day1SunSet.raise_()
        self.day1SunRise.raise_()
        self.day2SunSet.raise_()
        self.day2SunRise.raise_()
        self.button_clear0.raise_()
        self.button_clear1.raise_()
        self.button_clear2.raise_()
        self.day0RiseLabel.raise_()
        self.day1RiseLabel.raise_()
        self.day2RiseLabel.raise_()
        self.day0SetLabel.raise_()
        self.day1SetLabel.raise_()
        self.day2SetLabel.raise_()
        self.day1Desc.raise_()
        self.day2Desc.raise_()
        self.day1Date.raise_()
        self.day2Date.raise_()
        self.addLocation0.raise_()
        self.addLocation1.raise_()
        self.addLocation2.raise_()
        self.day1Humid.raise_()
        self.day2Humid.raise_()
        self.day1Wind.raise_()
        self.day2Wind.raise_()
        self.button_add1.raise_()
        self.button_add0.raise_()
        self.button_add2.raise_()

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.button_forecast0.setText(QCoreApplication.translate("Dialog", u"5 Day Forecast", None))
        self.button_forecast1.setText(QCoreApplication.translate("Dialog", u"5 Day Forecast", None))
        self.button_forecast2.setText(QCoreApplication.translate("Dialog", u"5 Day Forecast", None))
        self.button_add0.setText(QCoreApplication.translate("Dialog", u"+", None))
        self.button_add1.setText(QCoreApplication.translate("Dialog", u"+", None))
        self.button_add2.setText(QCoreApplication.translate("Dialog", u"+", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"\ud83c\udf08\ud83c\udf11\ud83c\udf19\ud83c\udf2c\ufe0f\ud83c\udf27\ufe0f\ud83c\udf0a\u26a1\ud83c\udf1a\u2603\ufe0f\u2744\ufe0f\ud83c\udf1dWelcome to the Weather App\ud83c\udf1e\ud83c\udf24\ufe0f\ud83c\udf26\ufe0f\ud83c\udf0b\ud83c\udf29\ufe0f\ud83c\udf2a\ufe0f\ud83c\udf1b\u2614\ud83c\udf28\ufe0f\ud83c\udf16\ud83c\udf08", None))
        self.day0Temp.setText(QCoreApplication.translate("Dialog", u"73\u00b0", None))
        self.day1Temp.setText(QCoreApplication.translate("Dialog", u"73\u00b0F", None))
        self.day2Temp.setText(QCoreApplication.translate("Dialog", u"102\u00b0F", None))
        self.day0Loc.setText(QCoreApplication.translate("Dialog", u"San Francisco, US", None))
        self.day1Loc.setText(QCoreApplication.translate("Dialog", u"Carlsbad, US", None))
        self.day2Loc.setText(QCoreApplication.translate("Dialog", u"Carlsbad, US", None))
        self.day0Desc.setText(QCoreApplication.translate("Dialog", u"clear sky", None))
        self.day0Date.setText(QCoreApplication.translate("Dialog", u"September 31     11:30 AM", None))
        self.day0RiseSymb.setText(QCoreApplication.translate("Dialog", u"\ud83c\udf05", None))
        self.day0SetSymb.setText(QCoreApplication.translate("Dialog", u"\ud83c\udf07", None))
        self.day1RiseSymb.setText(QCoreApplication.translate("Dialog", u"\ud83c\udf05", None))
        self.day1SetSymb.setText(QCoreApplication.translate("Dialog", u"\ud83c\udf07", None))
        self.day2RiseSymb.setText(QCoreApplication.translate("Dialog", u"\ud83c\udf05", None))
        self.day2SetSymb.setText(QCoreApplication.translate("Dialog", u"\ud83c\udf07", None))
        self.day0Humid.setText(QCoreApplication.translate("Dialog", u"\ud83d\udca7                  31% Humidity", None))
        self.day0Wind.setText(QCoreApplication.translate("Dialog", u"\ud83d\udca8                  Wind 5 mph", None))
        self.day0SunRise.setText(QCoreApplication.translate("Dialog", u"5:35 AM", None))
        self.day0SunSet.setText(QCoreApplication.translate("Dialog", u"7:48 PM", None))
        self.day1SunSet.setText(QCoreApplication.translate("Dialog", u"7:48 PM", None))
        self.day1SunRise.setText(QCoreApplication.translate("Dialog", u"5:35 AM", None))
        self.day2SunSet.setText(QCoreApplication.translate("Dialog", u"7:48 PM", None))
        self.day2SunRise.setText(QCoreApplication.translate("Dialog", u"5:35 AM", None))
        self.button_clear0.setText(QCoreApplication.translate("Dialog", u"Clear Location", None))
        self.button_clear1.setText(QCoreApplication.translate("Dialog", u"Clear Location", None))
        self.button_clear2.setText(QCoreApplication.translate("Dialog", u"Clear Location", None))
        self.day0RiseLabel.setText(QCoreApplication.translate("Dialog", u"Sunrise", None))
        self.day1RiseLabel.setText(QCoreApplication.translate("Dialog", u"Sunrise", None))
        self.day2RiseLabel.setText(QCoreApplication.translate("Dialog", u"Sunrise", None))
        self.day0SetLabel.setText(QCoreApplication.translate("Dialog", u"Sunset", None))
        self.day1SetLabel.setText(QCoreApplication.translate("Dialog", u"Sunset", None))
        self.day2SetLabel.setText(QCoreApplication.translate("Dialog", u"Sunset", None))
        self.day1Desc.setText(QCoreApplication.translate("Dialog", u"broken clouds", None))
        self.day2Desc.setText(QCoreApplication.translate("Dialog", u"overcast clouds", None))
        self.day1Date.setText(QCoreApplication.translate("Dialog", u"September 31     11:30 AM", None))
        self.day2Date.setText(QCoreApplication.translate("Dialog", u"September 31     11:30 AM", None))
        self.addLocation0.setText(QCoreApplication.translate("Dialog", u"Add Location", None))
        self.addLocation1.setText(QCoreApplication.translate("Dialog", u"Add Location", None))
        self.addLocation2.setText(QCoreApplication.translate("Dialog", u"Add Location", None))
        self.day1Humid.setText(QCoreApplication.translate("Dialog", u"\ud83d\udca7                  31% Humidity", None))
        self.day2Humid.setText(QCoreApplication.translate("Dialog", u"\ud83d\udca7                  31% Humidity", None))
        self.day1Wind.setText(QCoreApplication.translate("Dialog", u"\ud83d\udca8                  Wind 5 mph", None))
        self.day2Wind.setText(QCoreApplication.translate("Dialog", u"\ud83d\udca8                  Wind 5 mph", None))
    # retranslateUi

