# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ScreenForecast.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QLabel,
    QPushButton, QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(600, 350)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QSize(600, 350))
        Form.setMaximumSize(QSize(600, 350))
        self.buttonBack = QPushButton(Form)
        self.buttonBack.setObjectName(u"buttonBack")
        self.buttonBack.setGeometry(QRect(510, 310, 41, 23))
        font = QFont()
        font.setFamilies([u"Lucida Sans Unicode"])
        font.setPointSize(10)
        self.buttonBack.setFont(font)
        self.High = QLabel(Form)
        self.High.setObjectName(u"High")
        self.High.setGeometry(QRect(0, 210, 61, 41))
        self.High.setMinimumSize(QSize(20, 17))
        font1 = QFont()
        font1.setFamilies([u"Comic Sans MS"])
        font1.setPointSize(11)
        self.High.setFont(font1)
        self.High.setAlignment(Qt.AlignCenter)
        self.Low = QLabel(Form)
        self.Low.setObjectName(u"Low")
        self.Low.setGeometry(QRect(0, 250, 61, 41))
        self.Low.setFont(font1)
        self.Low.setAlignment(Qt.AlignCenter)
        self.line = QFrame(Form)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(50, 210, 21, 81))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(Form)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 200, 601, 20))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_3 = QFrame(Form)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(130, 210, 21, 81))
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.day0High = QLabel(Form)
        self.day0High.setObjectName(u"day0High")
        self.day0High.setGeometry(QRect(60, 210, 81, 41))
        font2 = QFont()
        font2.setFamilies([u"Lucida Sans Unicode"])
        font2.setPointSize(12)
        self.day0High.setFont(font2)
        self.day0High.setAlignment(Qt.AlignCenter)
        self.day0Low = QLabel(Form)
        self.day0Low.setObjectName(u"day0Low")
        self.day0Low.setGeometry(QRect(60, 249, 81, 41))
        self.day0Low.setFont(font2)
        self.day0Low.setAlignment(Qt.AlignCenter)
        self.day1High = QLabel(Form)
        self.day1High.setObjectName(u"day1High")
        self.day1High.setGeometry(QRect(140, 210, 81, 41))
        self.day1High.setFont(font2)
        self.day1High.setAlignment(Qt.AlignCenter)
        self.day1Low = QLabel(Form)
        self.day1Low.setObjectName(u"day1Low")
        self.day1Low.setGeometry(QRect(140, 249, 81, 41))
        self.day1Low.setFont(font2)
        self.day1Low.setAlignment(Qt.AlignCenter)
        self.day2High = QLabel(Form)
        self.day2High.setObjectName(u"day2High")
        self.day2High.setGeometry(QRect(220, 210, 81, 41))
        self.day2High.setFont(font2)
        self.day2High.setAlignment(Qt.AlignCenter)
        self.day2Low = QLabel(Form)
        self.day2Low.setObjectName(u"day2Low")
        self.day2Low.setGeometry(QRect(220, 249, 81, 41))
        self.day2Low.setFont(font2)
        self.day2Low.setAlignment(Qt.AlignCenter)
        self.day3High = QLabel(Form)
        self.day3High.setObjectName(u"day3High")
        self.day3High.setGeometry(QRect(300, 210, 81, 41))
        self.day3High.setFont(font2)
        self.day3High.setAlignment(Qt.AlignCenter)
        self.day3Low = QLabel(Form)
        self.day3Low.setObjectName(u"day3Low")
        self.day3Low.setGeometry(QRect(300, 249, 81, 41))
        self.day3Low.setFont(font2)
        self.day3Low.setAlignment(Qt.AlignCenter)
        self.day4High = QLabel(Form)
        self.day4High.setObjectName(u"day4High")
        self.day4High.setGeometry(QRect(380, 210, 81, 41))
        self.day4High.setFont(font2)
        self.day4High.setAlignment(Qt.AlignCenter)
        self.day4Low = QLabel(Form)
        self.day4Low.setObjectName(u"day4Low")
        self.day4Low.setGeometry(QRect(380, 249, 81, 41))
        self.day4Low.setFont(font2)
        self.day4Low.setAlignment(Qt.AlignCenter)
        self.FiveDayHighAvg = QLabel(Form)
        self.FiveDayHighAvg.setObjectName(u"FiveDayHighAvg")
        self.FiveDayHighAvg.setGeometry(QRect(460, 209, 81, 41))
        self.FiveDayHighAvg.setFont(font1)
        self.FiveDayHighAvg.setAlignment(Qt.AlignCenter)
        self.FiveDayHighAvg.setWordWrap(True)
        self.FiveDayLowAvg = QLabel(Form)
        self.FiveDayLowAvg.setObjectName(u"FiveDayLowAvg")
        self.FiveDayLowAvg.setGeometry(QRect(460, 250, 81, 41))
        self.FiveDayLowAvg.setFont(font1)
        self.FiveDayLowAvg.setAlignment(Qt.AlignCenter)
        self.FiveDayLowAvg.setWordWrap(True)
        self.fiveDayHighAvg = QLabel(Form)
        self.fiveDayHighAvg.setObjectName(u"fiveDayHighAvg")
        self.fiveDayHighAvg.setGeometry(QRect(540, 210, 61, 41))
        self.fiveDayHighAvg.setFont(font2)
        self.fiveDayHighAvg.setAlignment(Qt.AlignCenter)
        self.fiveDayLowAvg = QLabel(Form)
        self.fiveDayLowAvg.setObjectName(u"fiveDayLowAvg")
        self.fiveDayLowAvg.setGeometry(QRect(540, 249, 61, 41))
        self.fiveDayLowAvg.setFont(font2)
        self.fiveDayLowAvg.setAlignment(Qt.AlignCenter)
        self.line_4 = QFrame(Form)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(210, 210, 20, 81))
        self.line_4.setFrameShape(QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_5 = QFrame(Form)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(280, 210, 41, 81))
        self.line_5.setFrameShape(QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_6 = QFrame(Form)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(370, 210, 21, 81))
        self.line_6.setFrameShape(QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_7 = QFrame(Form)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(450, 210, 21, 81))
        self.line_7.setFrameShape(QFrame.Shape.VLine)
        self.line_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_8 = QFrame(Form)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(530, 210, 21, 81))
        self.line_8.setFrameShape(QFrame.Shape.VLine)
        self.line_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_9 = QFrame(Form)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(0, 240, 601, 20))
        self.line_9.setFont(font2)
        self.line_9.setFrameShape(QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_10 = QFrame(Form)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(-10, 210, 21, 81))
        self.line_10.setFrameShape(QFrame.Shape.VLine)
        self.line_10.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_11 = QFrame(Form)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(590, 210, 16, 81))
        self.line_11.setFrameShape(QFrame.Shape.VLine)
        self.line_11.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_12 = QFrame(Form)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(0, 280, 601, 21))
        self.line_12.setFrameShape(QFrame.Shape.HLine)
        self.line_12.setFrameShadow(QFrame.Shadow.Sunken)
        self.day0Date = QLabel(Form)
        self.day0Date.setObjectName(u"day0Date")
        self.day0Date.setGeometry(QRect(60, 290, 81, 20))
        font3 = QFont()
        font3.setFamilies([u"Verdana"])
        font3.setPointSize(11)
        self.day0Date.setFont(font3)
        self.day0Date.setAlignment(Qt.AlignCenter)
        self.day1Date = QLabel(Form)
        self.day1Date.setObjectName(u"day1Date")
        self.day1Date.setGeometry(QRect(140, 290, 81, 20))
        self.day1Date.setFont(font3)
        self.day1Date.setAlignment(Qt.AlignCenter)
        self.day2Date = QLabel(Form)
        self.day2Date.setObjectName(u"day2Date")
        self.day2Date.setGeometry(QRect(220, 290, 81, 20))
        self.day2Date.setFont(font3)
        self.day2Date.setAlignment(Qt.AlignCenter)
        self.day3Date = QLabel(Form)
        self.day3Date.setObjectName(u"day3Date")
        self.day3Date.setGeometry(QRect(300, 290, 81, 20))
        self.day3Date.setFont(font3)
        self.day3Date.setAlignment(Qt.AlignCenter)
        self.day4Date = QLabel(Form)
        self.day4Date.setObjectName(u"day4Date")
        self.day4Date.setGeometry(QRect(380, 290, 81, 20))
        self.day4Date.setFont(font3)
        self.day4Date.setAlignment(Qt.AlignCenter)
        self.graphicsView_forecast0 = QGraphicsView(Form)
        self.graphicsView_forecast0.setObjectName(u"graphicsView_forecast0")
        self.graphicsView_forecast0.setGeometry(QRect(60, 130, 75, 60))
        self.graphicsView_forecast0.setMinimumSize(QSize(75, 60))
        self.graphicsView_forecast0.setMaximumSize(QSize(75, 60))
        self.graphicsView_forecast0.setSizeIncrement(QSize(75, 60))
        self.graphicsView_forecast0.setBaseSize(QSize(75, 60))
        self.graphicsView_forecast1 = QGraphicsView(Form)
        self.graphicsView_forecast1.setObjectName(u"graphicsView_forecast1")
        self.graphicsView_forecast1.setGeometry(QRect(140, 130, 75, 60))
        self.graphicsView_forecast1.setMinimumSize(QSize(75, 60))
        self.graphicsView_forecast1.setMaximumSize(QSize(75, 60))
        self.graphicsView_forecast1.setSizeIncrement(QSize(75, 60))
        self.graphicsView_forecast1.setBaseSize(QSize(75, 60))
        self.graphicsView_forecast2 = QGraphicsView(Form)
        self.graphicsView_forecast2.setObjectName(u"graphicsView_forecast2")
        self.graphicsView_forecast2.setGeometry(QRect(220, 130, 75, 60))
        self.graphicsView_forecast2.setMinimumSize(QSize(75, 60))
        self.graphicsView_forecast2.setMaximumSize(QSize(75, 60))
        self.graphicsView_forecast2.setSizeIncrement(QSize(75, 60))
        self.graphicsView_forecast2.setBaseSize(QSize(75, 60))
        self.graphicsView_forecast3 = QGraphicsView(Form)
        self.graphicsView_forecast3.setObjectName(u"graphicsView_forecast3")
        self.graphicsView_forecast3.setGeometry(QRect(300, 130, 75, 60))
        self.graphicsView_forecast3.setMinimumSize(QSize(75, 60))
        self.graphicsView_forecast3.setMaximumSize(QSize(75, 60))
        self.graphicsView_forecast3.setSizeIncrement(QSize(75, 60))
        self.graphicsView_forecast3.setBaseSize(QSize(75, 60))
        self.graphicsView_forecast4 = QGraphicsView(Form)
        self.graphicsView_forecast4.setObjectName(u"graphicsView_forecast4")
        self.graphicsView_forecast4.setGeometry(QRect(380, 130, 75, 60))
        self.graphicsView_forecast4.setMinimumSize(QSize(75, 60))
        self.graphicsView_forecast4.setMaximumSize(QSize(75, 60))
        self.graphicsView_forecast4.setSizeIncrement(QSize(75, 60))
        self.graphicsView_forecast4.setBaseSize(QSize(75, 60))
        self.FiveDayForecast = QLabel(Form)
        self.FiveDayForecast.setObjectName(u"FiveDayForecast")
        self.FiveDayForecast.setGeometry(QRect(230, 30, 141, 20))
        font4 = QFont()
        font4.setFamilies([u"Lucida Sans Unicode"])
        font4.setPointSize(12)
        font4.setBold(True)
        self.FiveDayForecast.setFont(font4)
        self.FiveDayForecast.setAlignment(Qt.AlignCenter)
        self.forecastCity = QLabel(Form)
        self.forecastCity.setObjectName(u"forecastCity")
        self.forecastCity.setGeometry(QRect(0, 70, 601, 31))
        font5 = QFont()
        font5.setFamilies([u"Tahoma"])
        font5.setPointSize(16)
        self.forecastCity.setFont(font5)
        self.forecastCity.setAlignment(Qt.AlignCenter)
        self.day0Desc = QLabel(Form)
        self.day0Desc.setObjectName(u"day0Desc")
        self.day0Desc.setGeometry(QRect(60, 190, 81, 20))
        font6 = QFont()
        font6.setFamilies([u"Comic Sans MS"])
        font6.setPointSize(12)
        self.day0Desc.setFont(font6)
        self.day0Desc.setAlignment(Qt.AlignCenter)
        self.day1Desc = QLabel(Form)
        self.day1Desc.setObjectName(u"day1Desc")
        self.day1Desc.setGeometry(QRect(140, 190, 81, 20))
        self.day1Desc.setFont(font6)
        self.day1Desc.setAlignment(Qt.AlignCenter)
        self.day2Desc = QLabel(Form)
        self.day2Desc.setObjectName(u"day2Desc")
        self.day2Desc.setGeometry(QRect(220, 190, 81, 20))
        self.day2Desc.setFont(font6)
        self.day2Desc.setAlignment(Qt.AlignCenter)
        self.day3Desc = QLabel(Form)
        self.day3Desc.setObjectName(u"day3Desc")
        self.day3Desc.setGeometry(QRect(300, 190, 81, 20))
        self.day3Desc.setFont(font6)
        self.day3Desc.setAlignment(Qt.AlignCenter)
        self.day4Desc = QLabel(Form)
        self.day4Desc.setObjectName(u"day4Desc")
        self.day4Desc.setGeometry(QRect(380, 190, 81, 20))
        self.day4Desc.setFont(font6)
        self.day4Desc.setAlignment(Qt.AlignCenter)
        self.day0Low.raise_()
        self.day0High.raise_()
        self.day1High.raise_()
        self.buttonBack.raise_()
        self.High.raise_()
        self.Low.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.day1Low.raise_()
        self.day2High.raise_()
        self.day2Low.raise_()
        self.day3High.raise_()
        self.day3Low.raise_()
        self.day4High.raise_()
        self.day4Low.raise_()
        self.FiveDayHighAvg.raise_()
        self.FiveDayLowAvg.raise_()
        self.fiveDayHighAvg.raise_()
        self.fiveDayLowAvg.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.line_9.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.day0Date.raise_()
        self.day1Date.raise_()
        self.day2Date.raise_()
        self.day3Date.raise_()
        self.day4Date.raise_()
        self.graphicsView_forecast0.raise_()
        self.graphicsView_forecast1.raise_()
        self.graphicsView_forecast2.raise_()
        self.graphicsView_forecast3.raise_()
        self.graphicsView_forecast4.raise_()
        self.FiveDayForecast.raise_()
        self.forecastCity.raise_()
        self.day0Desc.raise_()
        self.day1Desc.raise_()
        self.day2Desc.raise_()
        self.day3Desc.raise_()
        self.day4Desc.raise_()

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.buttonBack.setText(QCoreApplication.translate("Form", u"Back", None))
        self.High.setText(QCoreApplication.translate("Form", u"High", None))
        self.Low.setText(QCoreApplication.translate("Form", u"Low", None))
        self.day0High.setText(QCoreApplication.translate("Form", u"63", None))
        self.day0Low.setText(QCoreApplication.translate("Form", u"53", None))
        self.day1High.setText(QCoreApplication.translate("Form", u"65", None))
        self.day1Low.setText(QCoreApplication.translate("Form", u"55", None))
        self.day2High.setText(QCoreApplication.translate("Form", u"71", None))
        self.day2Low.setText(QCoreApplication.translate("Form", u"54", None))
        self.day3High.setText(QCoreApplication.translate("Form", u"72", None))
        self.day3Low.setText(QCoreApplication.translate("Form", u"57", None))
        self.day4High.setText(QCoreApplication.translate("Form", u"74", None))
        self.day4Low.setText(QCoreApplication.translate("Form", u"61", None))
        self.FiveDayHighAvg.setText(QCoreApplication.translate("Form", u"High Avg", None))
        self.FiveDayLowAvg.setText(QCoreApplication.translate("Form", u"Low Avg", None))
        self.fiveDayHighAvg.setText(QCoreApplication.translate("Form", u"69", None))
        self.fiveDayLowAvg.setText(QCoreApplication.translate("Form", u"56", None))
        self.day0Date.setText(QCoreApplication.translate("Form", u"Jun, 11", None))
        self.day1Date.setText(QCoreApplication.translate("Form", u"Jun, 11", None))
        self.day2Date.setText(QCoreApplication.translate("Form", u"Jun, 11", None))
        self.day3Date.setText(QCoreApplication.translate("Form", u"Jun, 11", None))
        self.day4Date.setText(QCoreApplication.translate("Form", u"Jun, 11", None))
        self.FiveDayForecast.setText(QCoreApplication.translate("Form", u"5 Day Forecast", None))
        self.forecastCity.setText(QCoreApplication.translate("Form", u"Carlsbad, US", None))
        self.day0Desc.setText(QCoreApplication.translate("Form", u"Clear", None))
        self.day1Desc.setText(QCoreApplication.translate("Form", u"Rain", None))
        self.day2Desc.setText(QCoreApplication.translate("Form", u"Clouds", None))
        self.day3Desc.setText(QCoreApplication.translate("Form", u"Clear", None))
        self.day4Desc.setText(QCoreApplication.translate("Form", u"Clouds", None))
    # retranslateUi

